apiVersion: v2
name: monitoring
description: Monitoring stack for Portfolio infrastructure using kube-prometheus-stack
type: application
version: 0.2.0
appVersion: "1.0.0"
keywords:
  - monitoring
  - prometheus
  - grafana
  - alertmanager
home: https://github.com/jimjrxieb/LinkOps-Manifests
sources:
  - https://github.com/jimjrxieb/LinkOps-Manifests
maintainers:
  - name: LinkOps Team
    email: team@linkops.com

dependencies:
  - name: kube-prometheus-stack
    version: "65.1.1"
    repository: "https://prometheus-community.github.io/helm-charts"
    condition: kube-prometheus-stack.enabled
