apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.global.namespace }}
  labels:
    app.kubernetes.io/name: monitoring
    app.kubernetes.io/managed-by: Helm
    # Pod Security Standards
    pod-security.kubernetes.io/enforce: privileged  # Required for node-exporter
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged
